website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from werkzeug.security import generate_password_hash, check_password_hash
from .model import Users, Cards, db
from functools import wraps
import smtplib, os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from jinja2 import Template
from dotenv import load_dotenv

auth=Blueprint('auth', __name__)
load_dotenv()
HOST = "smtp.gmail.com"
PORT = 587
FROM_EMAIL = "linkup.tech.canada@gmail.com"
PASSWORD = os.getenv('LINKUP_EMAIL_PASSWORD')
TO_EMAIL = ""

class User:
    def __init__(self,email,password,linktree_card, direct_card):
        self.email = email
        self.password = password
        self.LT_card = linktree_card
        self.D_card = direct_card
        self.user_id=""
        self.organization = ""


def contains_num(s):
    for char in s:
        if char.isdigit():
            return True
    return False

def checkPassword(password, confirm_password):
    if len(password)<7:
            return 2
    elif password != confirm_password:
        return 3
    elif not contains_num(password):
        return 4
    return 1

def checkEmail(email, confirm_email):
    if not("@" in email or "." in email):
        return 2
    elif email != confirm_email:
        return 3
    return 1

def login_required(f):
    @wraps(f)
    def wrapper(*args, **kwargs):
        if "user" not in session:
            return redirect(url_for('auth.login_page'))
        return f(*args, **kwargs)
    return wrapper


def uniqueEmail(email):
    # cur = mysql.connection.cursor()
    try:
        user = Users.query.filter_by(email=email).first()
        if user:
            print(user)
            print(f"user with {email} already exist")
            print(Users.query.all())
            return False
        else:
            print(f"user with {email} does not exist")
            return True
    except Exception as e:
        print(f"Error: {e}")
        return False
    
def uniqueOrganization(organization):
    # cur = mysql.connection.cursor()
    try:
        # cur.execute("SELECT * FROM users WHERE organization = %s", (organization))
        # org = cur.fetchone()
        org = Users.query.filter_by(organization=organization).first()
        if org:
            print("Existing organization")
            return False
        else:
            return True
    except Exception as e:
            print(f"Error in uniqueOrganization: {e}")
            return False

def createUser(User):
    # cur = mysql.connection.cursor()
    hashed_password = generate_password_hash(User.password, method='pbkdf2:sha256')
    try:
        new_user = Users(organization=User.organization, email=User.email, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()
        # cur.execute("INSERT INTO users (organization,email,passwrd) VALUES (%s,%s,%s)", (User.organization,User.email,hashed_password))
        # mysql.connection.commit()
        # cur.close()
        # if cur.rowcount == 1:
        #     return 1
        # else:
        #     return 0
        print("user created")
        return 1
    except Exception as e:
            print(f"Error: {e}")
            return 0
    
def initializeCards(User):
    # cur = mysql.connection.cursor()
    try:
        # cur.execute("SELECT user_id FROM users WHERE email = %s", (User.email,))
        # user_id = cur.fetchone()
        user = Users.query.filter_by(email=User.email).first()
        if user:
            user_id = user.user_id

            #insert
            cards = Cards(user_id=user_id, organization=User.organization, email = User.email)
            db.session.add(cards)
            db.session.commit()
            return 1


        # cur.execute("INSERT INTO cards (user_id, organization, email) VALUES(%s,%s,%s)",(user_id,User.organization,User.email))
        # mysql.connection.commit()
        # cur.close()
        # if cur.rowcount == 1:
        #     return 1
        else:
            return 0
    except Exception as e:
        print(f"Error: {e}")
        return 0

def userExist(User):
    # cur = mysql.connection.cursor()
    try:
        # cur.execute("SELECT * FROM users WHERE email = %s", (User.email,))
        # result1 = cur.fetchone()
        user = Users.query.filter_by(email=User.email).first()
        if user:
            if check_password_hash(user.password, User.password):
                obj = {
                    'exist':1,
                    'id': user.user_id
                }
                return obj
            else:
                return {'exist':2}
        else: 
            return {'exist':0}   
    except Exception as e:
        print(f"Error: {e}")
        return {'exist': -1}
    


@auth.route("/login",methods=['GET','POST'])
def login_page():
    if request.method=="POST":
        session.pop("user", None)
        email = request.form['email']
        password = request.form['password']
        user = User(email, password,0,0)
        x = userExist(user)
        if x['exist']==1:
            session["user"] = user.email
            session["id"] = x['id']
            return redirect(url_for('views.home_page'))
        elif x['exist']==2:
            flash("Incorrect Password", category='error')
        elif x['exist']==0:
            flash("Invalid Credentials", category='error')
        else:
            flash("Authentication Error", category='error')
        
    return render_template('login.html', title="LOGIN", prompt="Create an account")

@auth.route("/signup",methods=['GET','POST'])
def signup_page():
    if request.method=="POST":
        session.pop("user", None)
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form["confirm password"]
        organization = request.form["organization"]
        
        check = checkPassword(password, confirm_password)
        if check == 2:
            flash('Password must be atleast 7 characters', category='error')
        elif check==3:
            flash('Passwords do not match', category='error')
        elif check==4:
            flash('Password must contain a number', category='error')
        elif not("@" in email or "." in email):
            flash('Email must contain an @ symbol', category='error')
        elif (organization != "") and (not(uniqueOrganization(organization))):
            flash('The organization name already exists', category='error')
        else:
            user = User(email,password,0,0)
            user.organization = organization
            x = uniqueEmail(user.email)
            if x:
                y = createUser(user)
                z = initializeCards(user)
                print(f"created user: {y}, initialized cards: {z}")
                if y and z:
                    flash("Account created!", category='success')                    
                    return redirect(url_for('auth.login_page'))
                else:
                    flash("Registration failed. Please try again", category='error')
            else:
                flash("An account with that email already exist", category='error')
    return render_template('signup.html', title="REGISTER", prompt="Log in to an existing account")

@auth.route("/logout")
def logout():
    session.pop("user", None)
    return redirect(url_for('auth.login_page'))

@auth.route("/recovery", methods=['GET','POST'])
def recovery_page():
    session.pop("user", None)
    if request.method == "POST":
        TO_EMAIL = request.form['email']
        #verify whether the email is valid
        valid = uniqueEmail(TO_EMAIL)
        if not valid:
            message = MIMEMultipart()
            message["From"] = FROM_EMAIL
            message["To"] = TO_EMAIL
            message["Subject"] = "LinkUp This is your Recovery URL"
            html_content = """
            <html>
            <body>
                <p>This is your recovery URL: {{ URL }}</p>
                <br>
                <p>LinkUp Canda</p>
                <p>linkup.tech.canada@gmail.com</p>                      
                <br>
            </body>
            </html>
            """
            template = Template(html_content)
            html = template.render(URL = "some URL")
            try:
                server = smtplib.SMTP(HOST,PORT)
                server.starttls()
                message.attach(MIMEText(html, 'html'))
                server.login(FROM_EMAIL,PASSWORD)
                server.sendmail(FROM_EMAIL,TO_EMAIL,message.as_string())
                server.quit()
                flash("Email sent successfully",category='success')
            except Exception as e:
                print(f"Sending Recovery Email: {e}")
                flash("Error in sending email. Try again",category='error')
        else:
            flash("Email not in the system",category='error')
    return render_template('recovery.html')

website/templates/OzzyBurger.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <link  rel="stylesheet" href="../static/css/OzzyBurger.css">
    <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
</head>
<body>
    <!-- <div class="bkg"></div> -->
    <section>
        <div class="head">
            <img class="logo" src="../static/assets/LinkUp-logo-Trans2.png" alt="linkup-logo">
        </div>
        <div class="head2">
            <h2> Ozzy Burgers </h2>
        </div>
        <div class="container">
            <div class="block">
                <a href="https://www.yelp.ca/writeareview/biz/vdR_vmmgfI56bwSZYYHtXg?return_url=%2Fbiz%2FvdR_vmmgfI56bwSZYYHtXg&review_origin=biz-details-war-button" target="_blank"><span class="icon1"><i class="fa-brands fa-google"></i></span></a>
            </div>
            <div class="block" id="block2">
                <a href="https://www.instagram.com/ozzysburgers/" target="_blank"><span class="icon2"><img class="ig" src="../static/assets/IG_logo1.png"></span></a>
            </div>
            <div class="block">
                <a  href="https://x.com/ozzysburgers?lang=en" target="_blank"><span class="icon3"><i class="fa-brands fa-x-twitter"></i></span></a>
            </div>
            <div class="block">
                <a href="https://www.youtube.com/watch?v=6d1NiDLiuqE" target="_blank"><span class="icon4"><i class="fa-brands fa-youtube"></i></span></a>
            </div>
        </div>
    </section>
    <!-- <div class="bkg"></div> -->
    
</body>
</html>

website/templates/PureVibes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  rel="stylesheet" href="../static/css/PureVibes.css">
    <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
    <title>LinkUp</title>
</head>
<body>
    <section>
        <div class="head">
            <img class="logo" src="../static/assets/LinkUp-logo-Trans2.png" alt="linkup-logo">
        </div>
        <div class="head2">
            <h2> Pure Vibes </h2>
        </div>
        <div class="container">
            <div class="block">
                <a href="#" target="_blank"><span class="icon1"><i class="fa-brands fa-google"></i></span></a>
            </div>
            <div class="block" id="block2">
                <a href="#" target="_blank"><span class="icon2"><img class="ig" src="../static/assets/IG_logo1.png"></span></a>
            </div>
            <div class="block">
                <a  href="#" target="_blank"><span class="icon3"><i class="fa-brands fa-x-twitter"></i></span></a>
            </div>
            <div class="block">
                <a href="#" target="_blank"><span class="icon4"><i class="fa-brands fa-youtube"></i></span></a>
            </div>
        </div>
    </section>
    
    <script scr="../static/javascript/business-x.js"></script>
</body>
</html>

website/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <link rel="stylesheet" href="../static/css/base.css">
    <link rel="stylesheet" href="../static/css/account.css">
    <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
    <script defer src="../static/javascript/account.js"></script>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="header-main-logo">
                <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-Logo-Trans2.png" alt="linkup-logo"></a>
            </div>
            <div class="nav-links">
                <ul class="links">
                    <li><a href="{{url_for('views.home_page')}}">Home</a></li>
                    <li><a href="{{url_for('views.contact_page')}}">Contact</a></li>
                    <li><a href="{{url_for('order.order_page')}}">Order</a></li>
                    <li><a href="{{url_for('account.signout')}}" class="action_btn">Sign out</a></li>
                </ul>
                <div class="toggle_btn">
                    <i class="fa-solid fa-bars"></i>
                </div>
            </div>
        </div>


        <div class="dropdown_menu">
            <li><a href="{{url_for('views.home_page')}}">Home</a></li>
            <li><a href="{{url_for('views.contact_page')}}">Contact</a></li>
            <li><a href="{{url_for('order.order_page')}}">Order</a></li>
            <li><a class="cur-page-dropdown" href="{{url_for('account.account_page')}}">My Account</a></li>
            <li><a href="{{url_for('account.signout')}}" class="action_btn">Sign out</a></li>
        </div>
    </header>
        
        <h2 class="title"> My Account </h2>

        <h3 id="direct_card_purchased">Direct Cards purchased:</h3>
        <h3 id="linktree_card_purchased">Linktree Cards purchased:</h3>
        <div class="info-box">
            <div class="btn-box">
                <button class="acc_toggle_btn" id="acc_btn">Account</button>
                <button class="acc_toggle_btn" id="ord_btn">Order History</button>
            </div>
            <div class="container">
                <div id="acc-container">
                    <div class="b">
                        <div class="email-info">
                            <p>Email:</p>
                            <p class="email"></p>
                        </div>
                        <div class="email-edit">
                            <button id="edit-email">Edit</button>
                        </div>
                    </div>
                    <div class="b">
                        <div class="password-info">
                            <p>Password:</p>
                            <p class="password">&#8226 &#8226 &#8226 &#8226 &#8226 &#8226 &#8226 &#8226 &#8226 &#8226 &#8226</p>
                        </div>
                        <div class="password-edit">
                            <button id="change-password">Change Password</button>
                        </div>
                    </div>
                </div>
                <!-- DIFFERENT DISPLAYS-->
                <div id="order-container">
                    <div class="menu">
                        <p >Date</p>
                        <p>Qty Link Tree Cards</p>
                        <p>Qty Direct Cards</p>
                        <p>Total</p>
                    </div>
                        <div class="scroll-box">
                        <ul clas="orders-list">
                            
                        </ul>
                        </div>
                </div>
            </div>
        </div>
        
    <footer>
        <div class="footer-logo">
            <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-logo-Trans_W.png" alt="linkup-logo"></a>
        </div>
        <div class="footer-links">
            <a href="{{url_for('views.home_page')}}">Home</a>
            <a href="{{url_for('views.contact_page')}}">Contact</a>
            <a href="{{url_for('order.order_page')}}">Order</a>
            <a href="{{url_for('analytic.dashboard')}}">Analytics</a>
        </div>
        
    </footer>
    <!--MODAL CONFIRM PASSWORD-->
    <div class="overlay" id="overlay"></div>
    <div class="modal-confirm-password">
        <div class="close-pcm">
            <i class="fa-solid fa-x"></i>
        </div>
        <form class="modal-sub-1" method="POST" action="{{ url_for('account.render_form') }}">
        <h2>Confirm your existing password</h2>
        
        <label for="confirm-password">Password</label>
        <input type="text" id="confirm-password" name="confirm-password" minlength="7">

        <div class="confirm-password-btns">
            <button class="cancel-password-button">Cancel</button>
            <input type="submit" class="confirm-password-button" id="password-confirmation" value="Confirm Password">

            {% with messages = get_flashed_messages() %}
            {% if messages %}
            {% for category, message in messages %}
                <div class="flash">
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
            {% endwith %}
        </form>
    </div>
</body>
</html>

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../static/css/base.css">
</head>
<body>
    <div>
    <div class="order-container">
        <div class="menu">
            <p >Date</p>
            <p>Qty Link Tree Cards</p>
            <p>Qty Direct Cards</p>
            <p>Total</p>
        </div>
            <div class="scroll-box">
            <ul clas="orders-list">
                <div class="order">
                    <p class="date">2024-07-20</p>
                    <p class="num-LT">0</p>
                    <p class="num-D">3</p>
                    <p class="total">$ 29.99</p>
                </div>

                <div class="order">
                    <p class="date">2024-06-10</p>
                    <p class="num-LT">1</p>
                    <p class="num-D">2</p>
                    <p class="total">$ 35.99</p>
                </div>
            </ul>
            </div>
    </div>
</div>
</body>
</html>

<!--  date, qnty LT card, qnty D card, Total Price-->

website/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <link rel="stylesheet" href="../static/css/base.css">
    <link  rel="stylesheet" href="../static/css/contact.css">
    <script defer src="../static/javascript/contact.js"></script>
    <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="header-main-logo">
                <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-Logo-Trans2.png" alt="linkup-logo"></a>
            </div>
            <div class="nav-links">
                <ul class="links">
                    <li><a href="{{url_for('views.home_page')}}">Home</a></li>
                    <li><a href="{{url_for('views.contact_page')}}">Contact</a></li>
                    <li><a href="{{url_for('order.order_page')}}">Order</a></li>
                    <li>
                        {% if prompt2 == "Sign out" %}
                            <a href="#" onclick="signout()" class="action_btn"> {{ prompt2 }} </a>
                        {% else %}
                            <a href="{{url_for('auth.logout')}}" class="action_btn"> {{ prompt2 }} </a>
                        {% endif %}
                    </li>
                </ul>
                <div class="toggle_btn">
                    <i class="fa-solid fa-bars"></i>
                </div>
            </div>
        </div>

        <div class="dropdown_menu">
            <li><a href="{{url_for('views.home_page')}}">Home</a></li>
            <li><a class="cur-page-dropdown" href="{{url_for('views.contact_page')}}">Contact</a></li>
            <li><a href="{{url_for('order.order_page')}}">Order</a></li>
            {% if prompt2 == "Sign out" %}
                <li><a href="{{url_for('account.account_page')}}">My Account</a></li>
            {% endif %}
            <li>
                {% if prompt2 == "Sign out" %}
                    <a href="#" onclick="signout()" class="action_btn"> {{ prompt2 }} </a>
                {% else %}
                    <a href="{{url_for('auth.logout')}}" class="action_btn"> {{ prompt2 }} </a>
                {% endif %}
            </li>
        </div>
    </header>

        <div class="contact-actions">
            <div class="contact-message">
                <form id="form">
                    <!-- <h1> Get In Touch</h1>
                    <label for="email">Email</label>
                    <input type="email" required placeholder="Email">
                    <br>
                    <label for="message">Message</label>
                    <textarea id="message">

                    </textarea>
                    <br>
                    <input type="submit">
                    <p id="sent">
                    </p> -->
                    <p>Email us at: <br> <span>linkup.canada@outlook.com</span></p>
                </form>
            </div>
            <div class="contact-phone">
                <p>Or call <span>123-456-7890</span></p>
            </div>
        </div>
        

    <footer>
        <div class="footer-logo">
            <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-logo-Trans_W.png" alt="linkup-logo"></a>
        </div>
        <div class="footer-links">
            <a href="{{url_for('views.home_page')}}">Home</a>
            <a href="{{url_for('views.contact_page')}}">Contact</a>
            <a href="{{url_for('order.order_page')}}">Order</a>
            <a href="{{url_for('analytic.dashboard')}}">Analytics</a>
        </div>
        
    </footer>
</body>
</html>

website/templates/home.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="../static/css/base.css">
        <link  rel="stylesheet" href="../static/css/home.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap" rel="stylesheet">
        <script defer src="../static/javascript/home.js"></script>
        <script src="https://kit.fontawesome.com/d218daeade.js" crossorigin="anonymous"></script>
        <title>LinkUp</title>
    </head>
    <body>
        <header>
            <div class="navbar">
                <div class="header-main-logo">
                    <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-Logo-Trans2.png" alt="linkup-logo"></a>
                </div>
                <div class="nav-links">
                    <ul class="links">
                        <li><a href="{{url_for('views.home_page')}}">Home</a></li>
                        <li><a href="{{url_for('views.contact_page')}}">Contact</a></li>
                        <li><a href="{{url_for('order.order_page')}}">Order</a></li>
                        <li>
                            {% if prompt2 == "Sign out" %}
                                <a href="#" onclick="signout()" class="action_btn"> {{ prompt2 }} </a>
                            {% else %}
                                <a href="{{url_for('auth.logout')}}" class="action_btn"> {{ prompt2 }} </a>
                            {% endif %}
                        </li>
                    </ul>
                    <div class="toggle_btn">
                        <i class="fa-solid fa-bars"></i>
                    </div>
                </div>
            </div>
                
            <div class="dropdown_menu">
                <li><a class="cur-page-dropdown" href="{{url_for('views.home_page')}}">Home</a></li>
                <li><a href="{{url_for('views.contact_page')}}">Contact</a></li>
                <li><a href="{{url_for('order.order_page')}}">Order</a></li>
                {% if prompt2 == "Sign out" %}
                    <li><a href="{{url_for('account.account_page')}}">My Account</a></li>
                {% endif %}
                <li>
                    {% if prompt2 == "Sign out" %}
                        <a href="#" onclick="signout()" class="action_btn"> {{ prompt2 }} </a>
                    {% else %}
                        <a href="{{url_for('auth.logout')}}" class="action_btn"> {{ prompt2 }} </a>
                    {% endif %}
                </li>
            </div>
        </header>
        <div class="content-box">
            <div class="text-box">
                <h1>Elevate your business with a flood of glowing customer reviews!</h1>
                <h3>With NFC technology, our cards  seamlessly bridge the gap between satisfied customers and your review site</h3>
                {% if prompt == "Sign in" %}
                    <a href="{{url_for('auth.logout')}}" class="order_btn">Boost your Reviews Today</a>
                {% else %}
                    <a href="{{url_for('order.order_page')}}" class="order_btn">Boost your Reviews Today</a>
                {% endif %}
            </div>
            <div class="scroll-box">
                <h1>
                    Our Connections
                </h1>
                <h2 class="order">
                    Order By
                </h2>
                <div class="order-container">
                    <button class="order-btn" id="card_btn">Cards In Use</button>
                    <button class="order-btn" id="date_btn">Date Joined</button>
                </div>
                <div class="container">
                    <ul class="orgs">
                    </ul>
                </div>
            </div>
        </div>
        <div class="content-box2">
            <div class="box1">
                <img src="../static/assets/LinkUp-card.png" alt="" srcset="">
            </div>
            <div class="text2">
                <p><span>Your business provides excellent products and services but</span>, you have trouble converting satisfied customers into positive reviews.</p>
                <br>
                <p class="text">Do you have an overcomplicated review process, lack an actionable incentive to present to your customers at the end of service,
                      or have no way of getting customers to know about your online presence?</p>
                    <br>
                <p class="text"><span>Our Solution:</span> Link Up cards provide a way to compile your entire online presence in one spot,
                    give them an actionable incentive at the end of their service, and direct them there instantly by simply scanning the card.</p>
            </div>
        </div>

        <footer>
            <div class="footer-logo">
                <a href="{{url_for('views.home_page')}}"><img src="../static/assets/LinkUp-logo-Trans_W.png" alt="linkup-logo"></a>
            </div>
            <div class="footer-links">
                <a href="{{url_for('views.home_page')}}">Home</a>
                <a href="{{url_for('views.contact_page')}}">Contact</a>
                <a href="{{url_for('order.order_page')}}">Order</a>
                <a href="{{url_for('analytic.dashboard')}}">Analytics</a>
            </div>
            
        </footer>
    </body>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <link rel="stylesheet" href="../static/css/auth.css">
</head>
<body>


    <section>
        <h2>{{ title }}</h2>
        <form method="POST">
            <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required placeholder="Email">
            </div>
            <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password"  required placeholder="Password">
            </div>
            <br>
            <input type="submit" value="Log In">
        </form>
        <a href="{{url_for('auth.signup_page')}}">{{prompt}}</a>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
                <div class="alert-danger">
                    {{ message }}
                </div>
            {% else %}
                <div class="alert-success">
                    {{ message }}
                </div>
            {% endif %}
            {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="logo">
            <img src="../static/assets/LinkUp-Logo-Trans2.png" alt="linkup-logo">
        </div>
    </section>
    
</body>
</html>

website/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LinkUp</title>
    <link rel="stylesheet" href="../static/css/auth.css">
</head>
<body>

    <section>
        <h2>{{ title }}</h2>
        <form method="POST">
            <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email"  placeholder="Email">
            </div>
            <div>
            <label for="password">Password:</label>
            <input type="password" id="password" name="password"  placeholder="Password">
            </div>
            <div>
            <label for="confirm password">Confirm Password:</label>
            <input type="password" id="confirm password" name="confirm password" placeholder="Confirm Password">
            </div>
            <div>
            <label for="organization">Organization Name <span>(If applicable)</span>:</label>
            <input type="text" id="organization" name="organization" placeholder="Name of your organization">
            </div>
            <br>
            <input type="submit" value="Register">
        </form>
        <a href="{{url_for('auth.login_page')}}">{{ prompt }}</a>
        <a href="{{url_for('auth.recovery_page')}}">Forgot your password?</a>
    
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == 'error' %}
            <div class="alert-danger">
                {{ message }}
            </div>
        {% else %}
            <div class="alert-success">
                {{ message }}
            </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="logo">
        <img src="../static/assets/LinkUp-Logo-Trans2.png" alt="linkup-logo">
    </div>
    </section>
</body>
</html>